global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flink'
    static_configs:
      - targets: ['taskmanager:9250', 'jobmanager:9250']
    scrape_interval: 10s
    
  - job_name: 'model-server'
    static_configs:
      - targets: ['model-server:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  - "alerts.yml"